### PR TITLE
licenses: fix typo

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by saud990** [comment]
https://github.com/google/licensecheck/commit/db1987b6bdd30a6777a02509214b17063deff3c8

**Comment by leuasseurfarrelds247-arch** [comment]
> Please take a look.

**Comment by leuasseurfarrelds247-arch** [comment]
> Please take a look.

**Comment by leuasseurfarrelds247-arch** [comment]
> Please take a look.

**Review by Mohammedsapry — APPROVED** [review]

**Pull request merged**
